export * from './create-user-profile-args.type';
export * from './update-user-profile-args.type';
export * from './update-user-favorites-animes-inpute.type';
export * from './update-user-favorites-authors-inpute.type';
export * from './update-user-favorites-characters-inpute.type';
export * from './update-user-favorites-genres-inpute.type';
export * from './update-user-favorites-studios-inpute.type';
export * from './get-user-profile-inpute.type';
export * from './update-user-favorites-collections-inpute.type';
