export const authorData = async () => [
    {
        id: '1347a799-c5e1-4326-9bec-f6eb5e6e087e',
        name: 'Хаяо Миядзаки',
        bucket_id: 'd2c94865-3981-406b-a9e6-1f15a62019a1',
        primary_occupations: [
            'Писатель',
            'Сценарист',
            'Продюсер',
            'Писатель',
            'Мангака',
            'Режиссёр',
        ],
        synonyms: ['Hayao Miyazaki', '宮崎駿'],
        bio: 'Всемирно известный японский автор аниме и манги',
        age: 20,
        years_active: ['1963', 'Present'],
        date_of_birth: '1900',
        date_of_death: '1990',
        home_town: 'London',
        blood_type: '2',
        language: 'eng',
        gender: 'male',
    },
    {
        id: '3027030a-65ee-45c3-9c1b-2dae2444a5e9',
        name: 'Харуки Мураками',
        primary_occupations: ['Писатель', 'Переводчик'],
        synonyms: ['Haruki Murakami', '村上春樹'],
        bucket_id: 'd2c94865-7575-406b-a9e6-1f15a98364a1',
        years_active: ['1985', 'Present'],
        bio: 'Об этом авторе не слышали разве что младенцы',
        age: 25,
        date_of_birth: '1900',
        date_of_death: '1990',
        home_town: 'London',
        blood_type: '2',
        language: 'eng',
        gender: 'male',
    },
    {
        id: '996e603b-d3dc-4fd8-b6fe-f5e2837168e5',
        name: 'Depeshe Mode',
        primary_occupations: ['Композитор'],
        bucket_id: 'd2c94865-7575-406b-a9e6-1f15a98364a1',
        synonyms: ['デペッシュ・モード', 'Режим депеши'],
        years_active: ['2011', 'Present'],
        bio: 'Synth wave',
        age: 35,
        date_of_birth: '1900',
        date_of_death: '1990',
        home_town: 'London',
        blood_type: '2',
        language: 'eng',
        gender: 'male',
    },
    {
        id: '43580db0-1e6f-463d-82d5-883aeae2457f',
        name: 'Rammstein',
        primary_occupations: ['Композитор'],
        bucket_id: 'd2c94865-7575-406b-a9e6-1f15a98364a1',
        synonyms: ['Раммштайн', 'ラムシュタイン'],
        years_active: ['1990', 'Present'],
        bio: 'Rock',
        age: 45,
        date_of_birth: '1900',
        date_of_death: '1990',
        home_town: 'London',
        blood_type: '2',
        language: 'eng',
        gender: 'male',
    },
    {
        id: 'ea5a020b-40ad-402a-8215-e9050a817b64',
        name: 'The Architects',
        primary_occupations: ['Мангака', 'Режиссёр', 'Композитор'],
        bucket_id: 'd2c94865-7575-406b-a9e6-1f15a98364a1',
        synonyms: ['Архитекторы', '建築家'],
        years_active: ['2005', '2018'],
        bio: 'Metal core',
        age: 65,
        date_of_birth: '1900',
        date_of_death: '1990',
        home_town: 'London',
        blood_type: '2',
        language: 'eng',
        gender: 'male',
    },
    {
        id: '4bc5062e-b024-4477-84cc-59f4ac203b11',
        name: 'Хидэаки Сорати',
        primary_occupations: ['Мангака'],
        age: 43,
        date_of_birth: 'May 25, 1979',
        date_of_death: '',
        synonyms: ['Hideaki Sorachi', '空知英秋 '],
        years_active: ['2003', 'Present'],
        home_town: 'Сорати, Япония',
        blood_type: '4',
        language: 'jpn',
        gender: 'male',
        bucket_id: 'd9a1d7bd-f8a0-44a5-89b6-1973fe92ac63',
        bio:
            'Японский мангака, наиболее известной его работой ' +
            'является манга Gintama. ' +
            'Сорати, по его словам, сильно интересовался мангой в детстве.',
    },
    {
        id: '74f44b75-75e5-4922-a5ba-4c1fd4d614f6',
        name: 'Тидзуру Мияваки',
        primary_occupations: ['Режиссёр'],
        age: 46,
        date_of_birth: '1976',
        date_of_death: '',
        synonyms: ['Chizuru Miyawaki', '宮脇千鶴 '],
        years_active: ['1997', 'Present'],
        home_town: 'Оита, Япония',
        blood_type: '2',
        language: 'jpn',
        gender: 'female',
        bucket_id: 'd9a1d7bd-f8a0-44a5-89b6-1973fe92ac63',
        bio: 'Режиссёр аниме',
    },
    {
        id: 'f505131e-4d9f-4e3c-a3a0-cb5b2751fc9d',
        name: 'Рюити Кимура',
        primary_occupations: ['Режиссёр'],
        age: 51,
        date_of_birth: 'Jun 10, 1971',
        date_of_death: '',
        synonyms: ['Ryuuichi Kimura', '木村隆一'],
        years_active: ['1995', 'Present'],
        home_town: 'Токио, Япония',
        blood_type: '1',
        language: 'jpn',
        gender: 'male',
        bucket_id: 'd9a1d7bd-f8a0-44a5-89b6-1973fe92ac63',
        bio: 'Режиссёр анимации',
    },
    {
        id: 'c8d6cd01-a845-41b7-878d-f495809fc36f',
        name: 'Мисудзу Тиба',
        primary_occupations: [],
        age: 24,
        date_of_birth: '1999',
        date_of_death: '',
        synonyms: ['Misuzu Chiba', '千葉美鈴'],
        years_active: ['2015', 'Present'],
        home_town: 'Токио, Япония',
        blood_type: '1',
        language: 'jpn',
        gender: 'female',
        bucket_id: 'd9a1d7bd-f8a0-44a5-89b6-1973fe92ac63',
        bio: 'Участник аниме проектов',
    },
    {
        id: '225662ac-0888-4bf1-a252-2e53b41e446c',
        name: 'Нацуки Такая',
        primary_occupations: ['Мангака'],
        age: 49,
        date_of_birth: 'Jul 7, 1973 ',
        date_of_death: '',
        synonyms: ['Natsuki Takaya', '高屋奈月'],
        years_active: ['1992', 'Present'],
        home_town: 'Токио, Япония',
        blood_type: '2',
        language: 'jpn',
        gender: 'female',
        bucket_id: 'd9a1d7bd-f8a0-44a5-89b6-1973fe92ac63',
        bio:
            'Родилась 7 июля 1973 года в японской префектуре Сидзуока. ' +
            'Левша. Дебютировала в качестве мангаки в 1992 году. ' +
            'Наиболее известная работа — «Корзинка фруктов».',
    },
    {
        id: '3f2fb7e6-6f94-40bc-ab31-f8d90a0df134',
        name: 'Таку Кисимото',
        primary_occupations: ['Сценарист'],
        age: 47,
        date_of_birth: 'May, 1975 ',
        date_of_death: '',
        synonyms: ['Taku Kishimoto', '岸本卓'],
        years_active: ['2005', 'Present'],
        home_town: 'Хёго, Япония',
        blood_type: '1',
        language: 'jpn',
        gender: 'male',
        bucket_id: 'd9a1d7bd-f8a0-44a5-89b6-1973fe92ac63',
        bio:
            'Японский сценарист аниме. ' +
            'После ухода из Studio Ghibli он был назначен ' +
            'ответственным за написание сценария для Bunny Drop. ' +
            'После его завершения он работал над несколькими ' +
            'сериалами, некоторые из которых - Haikyu !!, Erased и ' +
            'римейк Fruits Basket.',
    },
    {
        id: '6e190a1c-3dd4-4140-91ce-5d706e20c00b',
        name: 'Юдзуру Татикава',
        primary_occupations: ['Режиссёр'],
        age: 41,
        date_of_birth: 'Dec 2, 1981',
        date_of_death: '',
        synonyms: ['Yuzuru Tachikawa', '立川譲'],
        years_active: ['2006', 'Present'],
        home_town: 'Сайтама, Япония',
        blood_type: '3',
        language: 'jpn',
        gender: 'male',
        bucket_id: 'd9a1d7bd-f8a0-44a5-89b6-1973fe92ac63',
        bio:
            'Японский режиссер аниме. ' +
            'Начав свою карьеру в Madhouse, ' +
            'он известен как режиссер аниме-сериалов ' +
            '«Парад смерти», «Моб Психо 100» и «Дека-Денс».',
    },
    {
        id: 'c287a823-3976-467e-a093-9d7b9f65c544',
        name: 'Госё Аояма',
        primary_occupations: ['Мангака'],
        age: 59,
        date_of_birth: 'Jun 21, 1963 ',
        date_of_death: '',
        synonyms: ['Gosho Aoyama', '青山剛昌'],
        years_active: ['1985', 'Present'],
        home_town: 'Тоттори, Япония',
        blood_type: '4',
        language: 'jpn',
        gender: 'male',
        bucket_id: 'd9a1d7bd-f8a0-44a5-89b6-1973fe92ac63',
        bio:
            'Мангака, наиболее известен как создатель манги ' +
            '«Детектив Конан». Настоящее имя Ёсимаса Аояма.',
    },
    {
        id: '60c1958e-9938-4ddd-b515-1ada1961ae0d',
        name: 'Томохиса Тагути',
        primary_occupations: [
            'Аниматор',
            'Режиссёр',
            'Художник-раскадровщик',
            'Сценарист',
        ],
        age: 37,
        date_of_birth: 'Apr 27, 1985',
        date_of_death: '',
        synonyms: ['Tomohisa Taguchi', '田口智久'],
        years_active: ['2008', 'Present'],
        home_town: 'Окаяма, Япония',
        blood_type: '2',
        language: 'jpn',
        gender: 'male',
        bucket_id: 'd9a1d7bd-f8a0-44a5-89b6-1973fe92ac63',
        bio: 'Японский аниматор, режиссер, художник-раскадровщик и сценарист.',
    },
    {
        id: '6a6d7780-a4f8-43da-8a6b-50ba6befff11',
        name: 'Тайто Кубо',
        primary_occupations: ['Мангака'],
        age: 45,
        date_of_birth: 'Jun 26, 1977 ',
        date_of_death: '',
        synonyms: ['Tite Kubo', '久保帯人'],
        years_active: ['1996', 'Present'],
        home_town: 'Хиросима, Япония',
        blood_type: '3',
        language: 'jpn',
        gender: 'male',
        bucket_id: 'd9a1d7bd-f8a0-44a5-89b6-1973fe92ac63',
        bio:
            'Тайто Кубо, настоящее имя Нориаки Кубо — японский мангака. ' +
            'Он наиболее известен своей мангой «Блич». ' +
            'Часто встречаются ошибочные варианты написания его псевдонима, ' +
            'например: Титэ Кубо, Кубо Тайт, Куботайт, Куботайто, Куботитэ.',
    },
    {
        id: 'e688bb57-ecdf-416a-957d-b8d8c5b57a5d',
        name: 'Тиаки Кон',
        primary_occupations: ['Режиссёр', 'Аниматор'],
        age: 50,
        date_of_birth: 'Sep 29',
        date_of_death: '',
        synonyms: ['Chiaki Kon', '今千秋'],
        years_active: ['1999', 'Present'],
        home_town: 'Чиба, Япония',
        blood_type: '3',
        language: 'jpn',
        gender: 'female',
        bucket_id: 'd9a1d7bd-f8a0-44a5-89b6-1973fe92ac63',
        bio:
            'Родилась 29 сентября в префектуре Тиба. ' +
            'Первоначально работала в студии Pierrot, где приняла участие в качестве' +
            'раскадровщика и/или режиссёра-постановщика в выпуске ряда аниме этой студии.',
    },
    {
        id: 'f2e513e0-ef4a-4d67-8119-c734c9df9b75',
        name: 'Коконэ Ната',
        primary_occupations: ['Мангака'],
        age: 23,
        date_of_birth: 'Sep 2000',
        date_of_death: '',
        synonyms: ['Kokone Nata', '那多ここね'],
        years_active: ['2013', 'Present'],
        home_town: 'Токио, Япония',
        blood_type: '2',
        language: 'jpn',
        gender: 'female',
        bucket_id: 'd9a1d7bd-f8a0-44a5-89b6-1973fe92ac63',
        bio: 'Японская мангака',
    },
    {
        id: '369f1fc2-e1b8-4448-82d5-24099f80eb4d',
        name: 'Хироси Кодзина',
        primary_occupations: ['Аниматор', 'Дизайнер', 'Режиссёр'],
        age: 59,
        date_of_birth: 'Jun 4, 1963',
        date_of_death: '',
        synonyms: ['Hiroshi Koujina', '神志那弘志'],
        years_active: ['1982', 'Present'],
        home_town: 'Кумамото, Япония',
        blood_type: '4',
        language: 'jpn',
        gender: 'male',
        bucket_id: 'd9a1d7bd-f8a0-44a5-89b6-1973fe92ac63',
        bio:
            'Японский аниматор, дизайнер персонажей и режиссер аниме. ' +
            'Его режиссерские работы включают « Гренадер» , ' +
            '« Маджин Тантей Ногами Нейро» , « Киба» , ' +
            '« Радуга - Ниша Рокубо но Шичинин» и аниме-адаптацию ' +
            '« Хантер X Хантер» 2011 года.',
    },
    {
        id: 'cb6faea1-d7d8-4a5e-bdcb-8fec9daa9587',
        name: 'Ёсихиро Тогаси',
        primary_occupations: ['Мангака'],
        age: 56,
        date_of_birth: 'Apr 27, 1966 ',
        date_of_death: '',
        synonyms: ['Yoshihiro Togashi', '冨樫義博'],
        years_active: ['1986', 'Present'],
        home_town: 'Синдзё, Япония',
        blood_type: '3',
        language: 'jpn',
        gender: 'male',
        bucket_id: 'd9a1d7bd-f8a0-44a5-89b6-1973fe92ac63',
        bio:
            'Японский мангака, автор популярных манга-сериалов ' +
            'YuYu Hakusho, Level E и Хантер X Хантер, ' +
            'которые издавались в журнале Weekly Shonen Jump.',
    },
    {
        id: 'e602ecea-435c-4419-9f50-890d3faaf808',
        name: 'Оуто',
        primary_occupations: ['Мангака'],
        age: 25,
        date_of_birth: 'May 29, 1998',
        date_of_death: '',
        synonyms: ['Uoto', '魚豊 '],
        years_active: ['2016', 'Present'],
        home_town: 'Токио, Япония',
        blood_type: '3',
        language: 'jpn',
        gender: 'male',
        bucket_id: 'd9a1d7bd-f8a0-44a5-89b6-1973fe92ac63',
        bio: 'Японский мангака, автор манги "Чи: О движении Земли',
    },
    {
        id: 'd4e62fc0-ff58-4e52-adea-b649ac4185ca',
        name: 'Цутому Мидзусима',
        primary_occupations: ['Режиссёр'],
        age: 57,
        date_of_birth: 'Dec 6, 1965',
        date_of_death: '',
        synonyms: ['Tsutomu Mizushima', '水島努 '],
        years_active: ['1986', 'Present'],
        home_town: 'Нагано, Япония',
        blood_type: '2',
        language: 'jpn',
        gender: 'male',
        bucket_id: 'd9a1d7bd-f8a0-44a5-89b6-1973fe92ac63',
        bio: 'Японский режиссёр аниме.',
    },
    {
        id: 'bc9ee071-5935-4d1f-a99f-9f2c1a0646e3',
        name: 'Фумикане Симада',
        primary_occupations: ['Иллюстратор', 'Дизайнер'],
        age: 48,
        date_of_birth: 'Jan 26, 1974 ',
        date_of_death: '',
        synonyms: ['Fumikane Shimada', '島田フミカネ'],
        years_active: ['1991', 'Present'],
        home_town: 'Окаяма, Япония',
        blood_type: '2',
        language: 'jpn',
        gender: 'male',
        bucket_id: 'd9a1d7bd-f8a0-44a5-89b6-1973fe92ac63',
        bio:
            'Иллюстратор аниме и видеоигр и дизайнер персонажей' +
            'из префектуры Окаяма.',
    },
    {
        id: 'a22c040f-c228-43e0-a628-35e82ed293d3',
        name: 'Харуюки Морисава',
        primary_occupations: ['Художник', 'Иллюстратор'],
        age: 27,
        date_of_birth: 'Sep 30, 1990',
        date_of_death: '',
        synonyms: ['Haruyuki Morisawa', '森沢晴行'],
        years_active: ['2004', 'Present'],
        home_town: 'Тояма, Япония',
        blood_type: '1',
        language: 'jpn',
        gender: 'male',
        bucket_id: 'd9a1d7bd-f8a0-44a5-89b6-1973fe92ac63',
        bio: 'Иллюстратор аниме из префектуры Тояма',
    },
    {
        id: '75f855d1-9148-434c-8552-07fdb1c277a4',
        name: 'Син Араки',
        primary_occupations: ['Мангака'],
        age: 55,
        date_of_birth: '1968',
        date_of_death: '',
        synonyms: ['Shin Araki', '新木伸'],
        years_active: ['1981', 'Present'],
        home_town: 'Токио, Япония',
        blood_type: '4',
        language: 'jpn',
        gender: 'male',
        bucket_id: 'd9a1d7bd-f8a0-44a5-89b6-1973fe92ac63',
        bio: 'Японский мангака',
    },
];
